### ISSUE TITLE
pip3 install crownstone_ble downloads an incompatible version of bleak

### ISSUE THREAD

**Issue by Mergon** [crownstone/crownstone-lib-python-ble#12]
A while back, I had some trouble with running the tools. After troubleshooting, it turned out that it was trying to run with bleak 0.11, which didn't work out. Downgrading to 0.10 solved it. Today I was messing around with the lib again, and I seemed to encounter the same problem, with bleak 0.12.1 being the automatic install this time. For now I'll just ``pip3 install bleak==0.10 --force-reinstall``, but this might warrant fixing.

**Comment by AlexDM0** [comment]
This has been addressed in the requirements and will be added to the next release. Thanks for the heads up!

**Comment by Mergon** [comment]
Cheers!
