### ISSUE TITLE
Function  ControlHandler never awaited?

### ISSUE THREAD

**Issue by mPlagge** [crownstone/crownstone-lib-python-ble#14]
https://github.com/crownstone/crownstone-lib-python-ble/blob/8f2318b2842c3500fb61f46c4868e65dcf9638d4/crownstone_ble/core/ble_modules/ControlHandler.py#L105

Got a runtime error, see log bellow

```
/usr/local/lib/python3.8/dist-packages/crownstone_ble/core/ble_modules/ControlHandler.py:105: RuntimeWarning: coroutine 'BleHandler.disconnect' was never awaited
  self.core.ble.disconnect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by vliedel** [comment]
Good catch, fixed in bbb24cfec6b2d3a1943e82b33e6f60e2d5bf964e
