### ISSUE TITLE
Timing / threading Issues with uploading microapps

### ISSUE THREAD

**Issue by mPlagge** [crownstone/crownstone-lib-python-ble#15]
In function:

https://github.com/crownstone/crownstone-lib-python-ble/blob/bbb24cfec6b2d3a1943e82b33e6f60e2d5bf964e/crownstone_ble/core/ble_modules/BleHandler.py#L316

Changing pol interval to 0.01 seems to resolve issue, or at least, make sure no python errors show up. Microapp seems up upload now.

https://github.com/crownstone/crownstone-lib-python-ble/blob/bbb24cfec6b2d3a1943e82b33e6f60e2d5bf964e/crownstone_ble/core/ble_modules/BleHandler.py#L333

**Comment by vliedel** [comment]
Properly fixed by https://github.com/crownstone/crownstone-lib-python-ble/commit/2e0f788b2916c07b9a8b25faf0393f8d40cc3148
Can you test if that works for you?

**Comment by mPlagge** [comment]
I tested the the fix, didn't seem to work

**Comment by vliedel** [comment]
Oops.
Fixed with https://github.com/crownstone/crownstone-lib-python-ble/commit/f48536651cee88076c79afce8679f10a59733cdf
