### ISSUE TITLE
BLE Connect function does not clear connected device after failed connection.

### ISSUE THREAD

**Issue by Kvanr23** [crownstone/crownstone-lib-python-ble#8]
# Problem

In the connect function: https://github.com/crownstone/crownstone-lib-python-ble/blob/57e6b97dedf398ffdcc4d6516283abe271af4dc9/crownstone_ble/core/ble_modules/BleHandler.py#L63

If the connection with the Crownstone fails, and the BTLEDisconnectError is raised, the address is kept as connected.
When checking the connection with for example `hcitool con` , it is clear that there is no connection with the device then.

# Solution
https://github.com/crownstone/crownstone-lib-python-ble/blob/57e6b97dedf398ffdcc4d6516283abe271af4dc9/crownstone_ble/core/ble_modules/BleHandler.py#L70-L72
Before the `return False` is issued, the address needs to be removed from self.connectedPeripheral and self.connectedPeripherals.
(Via a call to the disconnect function?)

Otherwise, a following attempt will result in "already connected", and this can mess up following code.

**Comment by AlexDM0** [comment]
Since we've moved to a different bluetooth lib, I think this issue can be closed. If the issue remains in the new library, please open a new issue.
